BINARY=main
STATIC_LIB=libfast.a
SHARED_LIB=libfast.so

SOURCE_DIR=source
INCLUDE_DIR=include
GET_DIR=fastget
RAND_DIR=fastrand
THREAD_DIR=fastthread

OBJECT_FILE_TARGET=OBJECT_FILE_TARGET

HGET_DIR=$(INCLUDE_DIR)/$(GET_DIR)
HRAND_DIR=$(INCLUDE_DIR)/$(RAND_DIR)
HTHREAD_DIR=$(INCLUDE_DIR)/$(THREAD_DIR)

SGET_DIR=$(SOURCE_DIR)/$(GET_DIR)
SRAND_DIR=$(SOURCE_DIR)/$(RAND_DIR)
STHREAD_DIR=$(SOURCE_DIR)/$(THREAD_DIR)

HGET_FILE=$(HGET_DIR)/*.h
HRAND_FILE=$(HRAND_DIR)/*.h
HTHREAD_FILE=$(HTHREAD_DIR)/*.h
HEAD_FILE=$(INCLUDE_DIR)/*.h

SGET_FILE=$(SGET_DIR)/*.cpp
SRAND_FILE=$(SRAND_DIR)/*.cpp
STHREAD_FILE=$(STHREAD_DIR)/*.cpp
SOURCE_FILE=$(BINARY).cpp

ALL_HFILE=$(HEAD_FILE) $(HGET_FILE) $(HRAND_FILE) $(HTHREAD_FILE)
ALL_SFILE=$(SGET_FILE) $(SRAND_FILE) $(STHREAD_FILE)

$(BINARY): $(SOURCE_FILE) $(STATIC_LIB)
	$(CXX) -o $(BINARY) $(SOURCE_FILE) $(STATIC_LIB)
$(STATIC_LIB): $(OBJECT_FILE_TARGET)
	$(AR) -r $(STATIC_LIB) *.o
$(SHARED_LIB): $(OBJECT_FILE_TARGET)
	$(CXX) -o $(SHARED_LIB) -shared *.o
$(OBJECT_FILE_TARGET): $(ALL_SFILE) $(ALL_HFILE)
	$(CXX) -fPIC -c $(ALL_SFILE)
	
.PHONY: shared clean static_lib shared_lib

shared: $(SOURCE_FILE) $(SHARED_LIB)
	$(CXX) -o $(BINARY) $(SOURCE_FILE) ./$(SHARED_LIB)
clean:
	$(RM) $(BINARY) *.o *.so *.a
	
static_lib: $(STATIC_LIB)
shared_lib: $(SHARED_LIB)